name: oas
on: [push, pull_request]

jobs:
  oas:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.x.x
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Gen documentation spec
        run: pnpm next-rest-framework generate

      - run: cat openapi.json
      - uses: EndBug/add-and-commit@v9
        with:
            add: 'openapi.json'
            fetch: true
            message: 'chore: updating openapi.json file'
            push: true
            default_author: github_actions